services:
  - docker

env:
  - DOCKER_USER=lordvlad
  - COMMIT=${TRAVIS_COMMIT::6}
  - REPO=lordvlad/docker-apacheds
 
script:
  - docker build -f Dockerfile -t $REPO:$COMMIT .

after_success:
  - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
  - export TAG=`if [ “$TRAVIS_BRANCH” == “master” ]; then echo “latest”; else echo $TRAVIS_BRANCH ; fi`
  - echo $REPO:$TAG:$COMMIT
  - docker tag $REPO:$COMMIT $REPO:$TAG
  - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
  - docker push $REPO
